version: '2'
services:
  cmr:
    image: inspectit/cmr:1.9.3.107
    ports:
      - "8182:8182"
    volumes:
      - ./CMR/config:/CMR/config
      - ./CMR/ci:/CMR/ci
  config-server:
    image: openapm/spring-petclinic-config-server:inspectit-oce-demo
    container_name: config-server
    environment:
      - INSPECTIT_SERVICE_NAME=config-server
      - INSPECTIT_CONFIG_FILE_BASED_PATH=/agentconfig
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT=9096
    mem_limit: 512M
    entrypoint: ["sh", "-c","
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -javaagent:/agent/inspectit-agent.jar -Dinspectit.repository=cmr:9070 -Dinspectit.agent.name=config-server
      -jar /app.jar"]
    volumes:
      - ./agentconfig/config-server:/agentconfig
      - ./agent:/agent
    ports:
      - 8888:8888
      - 9096:9096

  discovery-server:
    image: openapm/spring-petclinic-discovery-server:inspectit-oce-demo
    container_name: discovery-server
    environment:
      - INSPECTIT_SERVICE_NAME=discovery-server
      - INSPECTIT_CONFIG_FILE_BASED_PATH=/agentconfig
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT=9095
    mem_limit: 512M
    depends_on:
      - config-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom -Dinspectit.repository=cmr:9070 -Dinspectit.agent.name=discovery-server
      -javaagent:/agent/inspectit-agent.jar
      -jar /app.jar"]
    volumes:
      - ./agentconfig/discovery-server:/agentconfig
      - ./agent:/agent
    ports:
      - 8761:8761
      - 9095:9095

  customers-service:
    image: openapm/spring-petclinic-customers-service:inspectit-oce-demo
    container_name: customers-service
    environment:
      - INSPECTIT_SERVICE_NAME=customers-service
      - INSPECTIT_CONFIG_FILE_BASED_PATH=/agentconfig
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT=9091
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom -Dinspectit.repository=cmr:9070 -Dinspectit.agent.name=customers-service
      -javaagent:/agent/inspectit-agent.jar
      -jar /app.jar"]
    volumes:
      - ./agentconfig/customers-service:/agentconfig
      - ./agent:/agent
    ports:
      - 8081:8081
      - 9091:9091

  visits-service:
    image: openapm/spring-petclinic-visits-service:inspectit-oce-demo
    container_name: visits-service
    environment:
      - INSPECTIT_SERVICE_NAME=visits-service
      - INSPECTIT_CONFIG_FILE_BASED_PATH=/agentconfig
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT=9092
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom -Dinspectit.repository=cmr:9070 -Dinspectit.agent.name=visits-service
      -javaagent:/agent/inspectit-agent.jar
      -jar /app.jar"]
    volumes:
      - ./agentconfig/visits-service:/agentconfig
      - ./agent:/agent
    ports:
      - 8082:8082
      - 9092:9092

  vets-service:
    image: openapm/spring-petclinic-vets-service:inspectit-oce-demo
    container_name: vets-service
    environment:
      - INSPECTIT_SERVICE_NAME=vets-service
      - INSPECTIT_CONFIG_FILE_BASED_PATH=/agentconfig
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT=9093
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom -Dinspectit.repository=cmr:9070 -Dinspectit.agent.name=vets-service
      -javaagent:/agent/inspectit-agent.jar
      -jar /app.jar"]
    volumes:
      - ./agentconfig/vets-service:/agentconfig
      - ./agent:/agent
    ports:
      - 8083:8083
      - 9093:9093

  api-gateway:
    image: openapm/spring-petclinic-api-gateway:inspectit-oce-demo
    container_name: api-gateway
    environment:
      - INSPECTIT_SERVICE_NAME=api-gateway
      - INSPECTIT_CONFIG_FILE_BASED_PATH=/agentconfig
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT=9094
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom -Dinspectit.repository=cmr:9070 -Dinspectit.agent.name=api-gateway
      -javaagent:/agent/inspectit-agent.jar
      -jar /app.jar"]
    volumes:
      - ./agentconfig/api-gateway:/agentconfig
      - ./agent:/agent
    ports:
      - 8080:8080
      - 9094:9094

  influxdb:
    image: influxdb:1.7.1
    container_name: influxdb
    environment:
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    mem_limit: 512M

  grafana:
    image: openapm/grafana:inspectit-oce-demo
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=demo
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
    volumes:
      - ./grafana/provisioning/eum:/usr/share/grafana/custom/
    ports:
      - 3000:3000
    entrypoint: ["sh", "-c","grafana-cli plugins install grafana-worldmap-panel && grafana-cli plugins install grafana-piechart-panel && /run.sh"]

  firefox:
    image: selenium/node-firefox:3.141.59-krypton
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub

  selenium-hub:
    image: selenium/hub:3.141.59-krypton
    ports:
      - "4444:4444"
  selenium-side-runner:
    build: ./selenium/docker/
    image: openapm/selenium-side-runner:latest
    volumes:
      - './selenium/sides/:/sides/'
    environment:
      - TARGET_HOST=api-gateway
      - TARGET_PORT=8080
      - TARGET_URL=http://api-gateway:8080/
      - SELENIUM_HUB_HOST=selenium-hub
  data-generator:
    image: java:8-alpine
    volumes: 
      - './generator/:/generator/'
    working_dir: /generator  
    entrypoint: ["sh", "-c","
       java -jar time-series-data-generator-1.0-SNAPSHOT.jar"]
